# age = input('How old are you? ')
# print(f'On your next birthday, you will be {int(age) +1}')
# print()
# egg = input('How many egg cartons do you have? ')
# print(f'You have {int(egg)*12}')
print()
cookie = int(input('How many cookies are there? '))
people = int(input('How many people are there? '))
print(f'Each person may have {cookie / people} cookies')